### ISSUE TITLE
Amazon Music update broke Nuvola integration

### ISSUE THREAD

**Issue by theli-ua** [tiliado/nuvolaruntime#656] opened 2020-10-22 00:20 UTC
### Describe the bug
Amazon updated music.amazon.com website and nuvola integration no longer works.

Current status is not updated in mpris,  next/prev/play/pause no longer work

**Comment by a-m-s** [comment] 2020-10-22 14:58
Works for me, but I'm using music.amazon.co.uk. Maybe it's different?

**Comment by theli-ua** [comment] 2020-10-22 18:33
At least in they US I am seeing this new (frankly, quite ugly) UI:  https://imgur.com/dJz86fo

**Comment by a-m-s** [comment] 2020-10-23 08:51
Yup, that's different. :-(

I'm just about to go away on vacation, so I won't be able to fix it right away.

**Comment by a-m-s** [comment] 2020-10-23 09:03
If I go to music.amazon.com it just forwards me to music.amazon.co.uk. Some sort of VPN setup will be needed to reproduce this issue. :-(

**Comment by a-m-s** [comment] 2020-10-23 11:03
I wonder if we have one of those A-B test or phased roll-out deals going on here?

**Comment by fenryxo** [comment] 2020-10-24 10:57
> If I go to music.amazon.com it just forwards me to music.amazon.co.uk. Some sort of VPN setup will be needed to reproduce this issue. :-(

If you need a VPN service, I can provide you access to [Private Internet Access](https://www.privateinternetaccess.com/) VPN provide. I pay for it from Nuvola funds.

**Comment by fenryxo** [comment] 2020-10-24 11:05
@theli-ua, is there any way to disable the new UI? It isn't uncommon to enable the new design but let users disable it in preferences until the new design is fully tested.

**Comment by theli-ua** [comment] 2020-10-24 16:01
No, there is no such option.

**Comment by domdfcoding** [comment] 2020-10-29 08:23
For me the UK site has now changed to the new dark theme.

**Comment by halcyon22** [comment] 2020-10-29 12:34
Same problem for me (USA user). I don't see a way to go back to the old UI.

**Comment by theli-ua** [comment] 2020-11-04 22:52
Since there hasn't been any progress here yet
I kinda started trying to update this. https://github.com/theli-ua/nuvola-app-amazon-cloud-player 
I got artist/title/prev/next/pause/play/volume working so far.

I'm not sure I'll have time to properly wrap this up though

**Comment by fenryxo** [comment] 2020-11-05 15:39
Thanks @theli-ua, @a-m-s will look at it once he returns from vacation.

**Comment by ams-cs** [comment] 2020-11-09 09:16
I see the new interface now. I just need to find time to get to it.

**Comment by theli-ua** [comment] 2020-11-09 18:20
> I see the new interface now. I just need to find time to get to it.

Did you get a chance to look at my PR ?

**Comment by ams-cs** [comment] 2020-11-09 20:49
Sorry, no, I missed that. I've got most of it done now.
Only seeking left to do, I think.

**Comment by theli-ua** [comment] 2020-11-09 21:02
> Sorry, no, I missed that. I've got most of it done now.
> Only seeking left to do, I think.

Thats fine. As long as the upstream gets fixed. I have everything working in that PR for what its worth. (including seeking)

**Comment by a-m-s** [comment] 2020-11-09 23:45
OK, I've pushed the fix (forgot to add the issue number to the commit, sorry).

I kept most of what I had already done, but I stole the maestro stuff from @theli-ua (that made life easier, thanks!) 

I think it's all working. Getting the volume change to show in the interface is a bit ugly, but it works.

**Comment by a-m-s** [comment] 2020-11-09 23:46
@fenryxo Do you want me to make an issue for release 5.11?

**Comment by theli-ua** [comment] 2020-11-09 23:52
>but I stole the maestro stuff from @theli-ua (that made life easier, thanks!)

>Getting the volume change to show in the interface is a bit ugly, but it works.

Well, why don't you also just take the volume part of it as well? The code and behaviour look just so much cleaner without popping up a volume slider in the UI

**Comment by theli-ua** [comment] 2020-11-09 23:57
@a-m-s btw, setting volume via maestro did change volume slider in the UI for me. (unless its already visible, in which case it would be updated if hidden and shown again).   to be honest I don't think its worth it to support updating slider if its already visible, I don't really see a meaningful use case for that

**Comment by a-m-s** [comment] 2020-11-10 10:51
Ugh, the Circle CI build fails because "maestro" is defined outside the module, which fails the "standard" check (I fixed all the other issues already).

How can I fix that?  (I'm not a Javascript expert.)

**Comment by fenryxo** [comment] 2020-11-10 15:58
> Do you want me to make an issue for release 5.11?

Yes, please.

> Ugh, the Circle CI build fails because "maestro" is defined outside the module, which fails the "standard" check (I fixed all the other issues already).
> 
> How can I fix that? (I'm not a Javascript expert.)

You can add `/* global maestro */` to the top of the script.

**Comment by a-m-s** [comment] 2020-11-10 16:02
Now fixed.

**Comment by fenryxo** [comment] 2020-11-10 19:20
Please keep the issue open until a Flatpak package with the fix is released to avoid bug duplicates.

**Comment by fenryxo** [comment] 2020-11-11 21:04
Rebuilt flatpak has been published - script version 5.10.2 (2-g2a707a9).

**Closed by fenryxo** 2020-11-11 21:04 UTC
Labels: type: bug
