### ISSUE TITLE
Error in installing Nuvola.

### ISSUE THREAD

**Issue by white-space-dev** [tiliado/nuvolaruntime#626] opened 2020-08-08 17:07 UTC
Im trying to install Nuvola player on my Ubuntu 20.04. but everytime i try to install in via the cli, the following error pops up.

```
➜  ~ flatpak install nuvola eu.tiliado.Nuvola
Looking for matches…

eu.tiliado.Nuvola permissions:
    ipc                        network     pulseaudio         wayland
    x11                        dri         file access [1]    dbus access [2]
    system dbus access [3]

    [1] /sys/fs/cgroup/pids/system.slice:ro, /sys/module/i915:ro,
        /sys/module/nvidia:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf, eu.tiliado.*, org.gnome.SessionManager,
        org.gnome.SettingsDaemon, org.gnome.SettingsDaemon.MediaKeys,
        org.xfce.SessionManager
    [3] org.freedesktop.NetworkManager


        ID                    Branch     Op     Remote    Download
 1. [✗] eu.tiliado.Nuvola     stable     i      nuvola    22.1 kB / 99.5 MB

Error: While pulling app/eu.tiliado.Nuvola/x86_64/stable from remote nuvola: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.
error: Failed to install eu.tiliado.Nuvola: While pulling app/eu.tiliado.Nuvola/x86_64/stable from remote nuvola: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.
```

**Comment by fenryxo** [comment] 2020-08-15 12:03
Hello @white-space-dev. I apologize for the late reply as I was on vacation. It looks like a network issue rather than a Nuvola bug.

**Comment by fenryxo** [comment] 2020-08-15 12:39
I'm afraid I cannot reproduce your issue. I've just installed Nuvola on a clean Ubuntu 20.04 system without any problems. Is there something unusual with your network configuration? A proxy or VPN or example.

**Comment by fenryxo** [comment] 2020-09-24 20:44
Closing as there hasn't been any response to my question.

**Closed by fenryxo** 2020-09-24 20:44 UTC
Labels: need info, type: bug
