### ISSUE TITLE
Player does not retain dark theme after re launch

### ISSUE THREAD

**Issue by MikeSaleem** [tiliado/nuvolaruntime#615] opened 2020-06-19 17:03 UTC
I added the Nuvola repository to my Fedora 32 Gnome system and then installed the Deezer flatpak player. In preferences, I changed theme to **Dark**. When closing the player and restarting the player, the theme is back to: **Light** . When clicking on preferences, it reverts back immediately to the **Dark** theme without needing to choose setting again. This happens after every relaunch of the app.
Mike

**Comment by fenryxo** [comment] 2020-06-24 14:05
Hello @MikeSaleem, thanks for your bug report.

**Comment by fenryxo** [comment] 2020-07-05 13:26
I'm afraid I cannot reproduce your issue on a clean Fedora 32 installation. I opened Deezer, went on *Preferences* → *Appearance Tweaks*, toggled *Prefer a dark variant...* on and the dark variant was applied instantly. When I opened Deezer again, the dark variant was in use from the beginning.

Could you provide me with [debugging info](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) for `eu.tiliado.NuvolaAppDeezer`?

**Comment by MikeSaleem** [comment] 2020-07-08 03:10
Hi,
I'm afraid I cannot re establish the same set-up anymore as I change my system for reviews quite often. I did double check before writing
the bug report and it behaved as stated. Sorry, I cannot be of more help. Once a new version is out I could test it again.
Cheers!
Mike
On Sun, Jul 5, 2020 at 08:26, Jiří Janoušek  wrote:
 I'm afraid I cannot reproduce your issue on a clean Fedora 32 installation. I opened Deezer, went on Preferences → Appearance Tweaks, toggled Prefer a dark variant... on and the dark variant was applied instantly. When I opened Deezer again, the dark variant was in use from the beginning.
 Could you provide me with debugging info (https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) for eu.tiliado.NuvolaAppDeezer?

**Comment by fenryxo** [comment] 2020-08-15 12:40
I'm closing the issue but feel free to reopen it once the issue appears again.

**Closed by fenryxo** 2020-08-15 12:40 UTC
Labels: need info, type: bug
