### ISSUE TITLE
Media keys as global keybindings don't work after user session is locked and unlocked

### ISSUE THREAD

**Issue by sobwoofer** [tiliado/nuvolaruntime#473] opened 2018-09-21 10:36 UTC
Hot keys don't work after block linux account (like Super+L). need to restart nuvola again. They were working in previous version.
deezer 3.0.14 (14-gea80ffe)
nuvola 4.12.89 (89-g6488610)

**Comment by fenryxo** [comment] 2018-09-23 07:11
Hello @sobwoofer. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Do you mean global hot keys or in-app hot keys?
* Which [distribution and version](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-system) do you use?
* What is your [desktop environment](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-system)?
* Do you use Xorg or Wayland? If you use Wayland, is the issue reproducible with Xorg?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output). Use hot keys before locking the user session, then unlock it and try to use the hot keys again, then copy the output and attach it here as a text file.
* Is the issue always reproducible or does it happen randomly?

**Comment by sobwoofer** [comment] 2018-09-24 09:46
@fenryxo 
1. i mean both variants (but only media keywords on the keyboard) logitech YR0009
It has keys like play, pause...
![screenshot from 2018-09-24 11-47-53](https://user-images.githubusercontent.com/8058919/45945660-e20a8380-bff6-11e8-81d4-69a6d7b1a2c1.png)
Standart keys like "Ctrl+Shift+Alt+Up" are working ok on both variantes.
2.deezer 3.0.14 (14-gea80ffe)
   nuvola 4.12.89 (89-g6488610)
3. Ubuntu 18.04
4. no i don't use any these soft.
5. after unlock user session terminal didn't feel special hotkeys [debug.txt](https://github.com/tiliado/nuvolaruntime/files/2410321/debug.txt)
6. it's problem not randomly, i see it always after unlock user profile in my ubuntu

**Comment by fenryxo** [comment] 2018-09-24 16:03
> i mean both variants (but only media keywords on the keyboard) logitech YR0009
It has keys like play, pause...
> Standart keys like "Ctrl+Shift+Alt+Up" are working ok on both variantes.

Do I understand correctly that *only multimedia keys configured as global keyboard shortcuts* don't work but other global keyboard shortcuts work fine?

> no i don't use any these soft.

I don't know to which question this answer belongs to. Do you use a regular desktop environment (GNOME is the default in Ubuntu 18.04, but you can change it to Unity, KDE, XFCE, etc.) or a custom setup?

**Comment by fenryxo** [comment] 2018-09-25 10:28
In that case the media keys are handled directly by GNOME and the binding in Nuvola should not work at all. In fact, it is a mystery that it actually works before you lock your user session.

Could you try disabling your media keys shortcuts and to use Nuvola's [Multimedia keys feature](https://nuvola.tiliado.eu/docs/4/media_keys.html) instead?

**Comment by fenryxo** [comment] 2018-09-25 10:30
You may need to log out & log in back after that.

**Comment by sobwoofer** [comment] 2018-09-27 13:28
yes, it works) thanks a lot)

**Comment by fenryxo** [comment] 2018-09-27 13:49
I'm reopening this because there is some work to do. Nuvola should not let a user to set multimedia keys as global keybinding at all.

**Comment by fenryxo** [comment] 2018-10-15 07:57
[Released in Nuvola 4.13.0](https://medium.com/nuvola-news/nuvola-4-13-released-2fdf80c73742).

**Closed by fenryxo** 2018-10-15 07:57 UTC
Labels: status: to release, type: bug
