### ISSUE TITLE
High CPU usage under Wayland/Gnome 3

### ISSUE THREAD

**Issue by dannosaur** [tiliado/nuvolaruntime#364] opened 2017-07-31 07:56 UTC
Opening a new ticket rather than resurrecting old ones. Referencing #317 and #260 I'm seeing really high CPU usage when playing music. I'm using the Google Play Music app.

Stats:
Nuvola Player 3 3.0.9
Revision f79856a684ab9fbce31d814059a4fc20a51489c1
WebKitGTK 2.16.5
libsoup 2.58.1

Running on top of Fedora 26, Gnome shell 3.24.2. While playing music at the exact time of writing, WebKitWebProcess is pinned at around 60-70% on a 4 core machine, but I've seen it running in excess of 300%, thus causing my laptop to heat up significantly, and lag when the system load rises as a result (since this isn't the only thing running on my machine).

Let me know what else you need and how I can help track this down.

**Comment by fenryxo** [comment] 2017-07-31 15:48
Hello @dannosaur. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Is the issue reproducible with the GNOME Web browser (also known as Epiphany)?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* Do you use the default GTK theme (Adwaita)?

**Comment by dannosaur** [comment] 2017-08-01 13:43
- I'm unable to test with Epiphany as it's being a royal pain in the rear about flash. Flash is installed, it just doesn't pick up the fact that it's there. The fact that it wants flash despite GPM being an HTML5 site confuses me somewhat, but irrelevant in the context of what's going on here.
- Debug output attached. I ran it only for a short while, the second I started playing music, it pinned the CPU at ~250%, and remained that way until I exited it.
- I do use the Adwaita GTK+ theme.

Let me know if I can help further.

[nuvola-debug.txt](https://github.com/tiliado/nuvolaruntime/files/1190726/nuvola-debug.txt)

**Comment by fenryxo** [comment] 2017-08-05 11:56
> I'm unable to test with Epiphany as it's being a royal pain in the rear about flash. Flash is installed, it just doesn't pick up the fact that it's there. 

I forgot to tell you that you need to launch Epiphany with `GDK_BACKEND=x11` because Flash plugin is obviously not loaded if Epiphany runs in full-Wayland mode (that fraking Flash plugin needs x11).

> The fact that it wants flash despite GPM being an HTML5 site confuses me somewhat, but irrelevant in the context of what's going on here.

GPM needs Media Source Extensions (MSE) for HTML5 playback, which is not supported by WebKitGTK (and Epiphany) yet. That's why Flash plugin is needed. (BTW, [Nuvola 4.6 recently enabled MSE for BBC iPlayer](https://medium.com/nuvola-news/nuvola-4-6-released-afd958c4e361) and the goal of Nuvola 4.7 is to enable MSE for Google Play Music too to get rid of flash plugin.)

> Let me know if I can help further.

Could you try to reproduce the issue in Epiphany again but with `GDK_BACKEND=x11 epiphany`? Thanks.

**Comment by dannosaur** [comment] 2017-08-09 08:13
I've just managed to test this out. Using `GDK_BACKEND=x11 epiphany`, playing music from Google Play Music does not pin the CPU anywhere near as high as Nuvola does. The WebKitWebProcess in epiphany sits at around 10-12% CPU while playing. Shut that down, opened Nuvola and started playing and WebKitWebProcess jumped straight to 300ish% and stayed there.

**Comment by fenryxo** [comment] 2017-08-09 12:08
It would be great to know whether it affects Nuvola 4 too. Are you willing to check that? If yes, please [create a Tiliado account](https://tiliado.eu/accounts/signup/) and tell me your username. I'll then upgrade it to a developer account so that you can use [Nuvola 4](https://nuvola.tiliado.eu) for free.

**Comment by fenryxo** [comment] 2017-08-09 13:08
My guess is that f150fb57fd32ef5476793efe67794ae704eee091 is no-op because `HAVE_WEBKIT_x_yy` flags are not defined in Nuvola 3. Reticketed as #368.

**Comment by dannosaur** [comment] 2017-08-09 13:12
I've created an account, username is dannosaur.

Thanks.

**Comment by fenryxo** [comment] 2017-08-09 14:16
Account upgraded 👍

**Comment by dannosaur** [comment] 2017-08-09 18:19
Just installed Nuvola 4. The issue doesn't appear to be present there. In fact, comparing the CPU usage between Nuvola 4 and natively in Chrome, CPU hovers around 40-50% for both. So based on that, I'd suggest that whatever's causing this in Nuvola 3 is fixed in 4.

**Comment by fenryxo** [comment] 2017-08-09 19:31
It'll be fixed in Nuvola 3.0.10 later this month.

**Closed** 2017-09-02 06:08 UTC
Labels: bug
