### ISSUE TITLE
The play / pause button does not work correctly in YouTube Music

### ISSUE THREAD

**Issue by CristhianEcheverry** [tiliado/nuvolaruntime#526] opened 2019-05-29 02:28 UTC
**Ubuntu 19.04, GNOME**  
**Nuvola App Runtime** -> 4.16.4 (4-g819cdb2)
**Web app** -> YouTube Music
**YouTube Music Script** -> 1.3.0 (0-gbbf30d7)

**Bug:**
The play / pause button does not work correctly in the notification panel, when you click on the action but does not have an "animation" that changes the function, there is always the play icon.

**Debugging log:**
Runner: [DEBUG Δ017765us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Runner: [DEBUG Δ001753us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Runner: [DEBUG Δ003249us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [DEBUG Δ065370us Nuvola] AboutDialog.vala:54: Nuvola Apps 4.16.4 (4-g819cdb2)
Runner: [DEBUG Δ000035us Nuvola] AboutDialog.vala:56: YouTube Music script 1.3.0 (0-gbbf30d7)
Runner: [DEBUG Δ000021us Nuvola] AboutDialog.vala:60: Diorite 4.16.3
Runner: [DEBUG Δ000031us Nuvola] AboutDialog.vala:62: Chromium 73.0.3683.75

**Screenshots**

Player paused
![Captura de pantalla de 2019-05-28 21-25-10](https://user-images.githubusercontent.com/20938887/58524870-46d23b00-818f-11e9-8e80-d5f594542320.png)

Player running
![Captura de pantalla de 2019-05-28 21-25-17](https://user-images.githubusercontent.com/20938887/58524903-68332700-818f-11e9-987c-4f608ba19a20.png)

**Comment by fenryxo** [comment] 2019-05-29 08:43
Hello @CristhianEcheverry. Thanks for reporting the issue. I'll look at it at the weekend.

**Comment by fenryxo** [comment] 2019-06-01 15:45
Hello @CristhianEcheverry. I cannot reproduce the issue. Could you attach a debugging log? Don't forget to click the play/pause button in the notification panel a few times so that it appears in the log.

See https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output
for instructions on how to get a debugging log. Then save it as a text file (*.txt) and attach it to the bug report.

- Use the "Attach files by dragging & dropping or selecting them." feature available under the textbox.
- Never trim the logs or you will be asked to provide new complete logs.
- Don't use "pastebin" services as the logs there may disappear anytime.
- Don't attach screenshots of the terminal output. Use text files.

**Comment by CristhianEcheverry** [comment] 2019-06-01 15:55
[debug YoutubeMusic.txt](https://github.com/tiliado/nuvolaruntime/files/3243940/debug.YoutubeMusic.txt)

;)

**Comment by fenryxo** [comment] 2019-06-01 18:26
Fix committed to the source code repository and will be released with the next rebuild of Flatpak packages.

**Comment by fenryxo** [comment] 2019-06-02 09:00
Published as Nuvola 4.16.10 & YouTube Music script 1.3.2. Could anyone verify that the issue is fixed?

**Comment by CristhianEcheverry** [comment] 2019-06-02 14:19
Solved, thank you :)

**Closed** 2019-06-03 13:09 UTC
Labels: need info, status: in progress, type: bug
