### ISSUE TITLE
Play/Pause buttons not working properly at Deezer Podcast

### ISSUE THREAD

**Issue by guiAlberto** [tiliado/nuvolaruntime#495] opened 2019-01-07 20:16 UTC
### Basic information

- Your Linux distribution and its version: Ubuntu 16.04.5 LTS
   

- Your desktop environment: Unity
   

 - Nuvola Runtime version: 4.15.0 (0-g06de715)
   

 - The web app you use and its version: Deezer 3.1.0 (0-g44ee7ae)
   

### Describe the bug

When listening to a Podcast at Deezer, the Play/Pause button does not work properly. It actualy goes back 30 seconds instead of pausing.

**Steps to reproduce the behavior**

1. Go to any Deezer Podcast
2. Click on Play at some episode
3: While playing the podcast, send the Play/Pause keyboard command.
4. The podcast's episode does not Pause. Instead, it comes back 30 seconds.

**Expected behavior**

The epidose should pause.

**Debugging log**

Attach the debug log here: 
[deezer.log](https://github.com/tiliado/nuvolaruntime/files/2734170/deezer.log)

**Screenshots**

![deezer](https://user-images.githubusercontent.com/18057706/50791138-09d0df00-12a8-11e9-901d-b519bb42a77c.gif)

**Additional context**

This issue does not affect the music player. It only occurs at the podcast.

**Comment by fenryxo** [comment] 2019-01-08 10:17
Hello @guiAlberto. Thanks for taking the time to report this issue. It seems I need to use VPN to test podcasts.

> [Where to find podcasts on Deezer](https://support.deezer.com/hc/en-gb/articles/115004522029-Podcasts)
> Podcasts on Deezer are primarily available to users in Austria, Brazil, France, Germany, Ireland, Switzerland, United Kingdom, and the United States.

**Comment by fenryxo** [comment] 2019-01-10 15:31
Hello @guiAlberto. Could you verify that the issue is fixed in the latest build? It's Deezer 3.1.2 with Nuvola 4.15.3 and Diorite 4.15.21.

**Comment by guiAlberto** [comment] 2019-01-14 12:55
@fenryxo it's working fine now. Thanks a lot.

**Comment by fenryxo** [comment] 2019-01-14 13:21
Great :-)

**Closed by fenryxo** 2019-01-14 13:21 UTC
Labels: need info, status: in progress, type: bug
