### ISSUE TITLE
allowed_uri seems broken

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvolaruntime#425] opened 2018-04-24 09:22 UTC
I've set an `allowed_uri` in the BBC app, but it doesn't appear to have any affect.

My setting looks like this:
```
"allowed_uri": "^https?://www.bbc.co.uk",
```
and I've confirmed that it appears in the `metadata.json` file.

However, if I go to [this page](http://www.bbc.co.uk/guides/zqnm2nb), for example, and click the "science museum" link, it happily goes to youtube.com without using an external browser.

Here's a log capture of me doing that: [log.txt](https://github.com/tiliado/nuvolaruntime/files/1942029/log.txt)

Interestingly, if I close the app while the youtube page is open, and then relaunch, it does not reopen the youtube page, but instead sends it to the external browser.

**Comment by fenryxo** [comment] 2018-04-24 10:33
Thanks @a-m-s. Could you attach the debugging output of `nuvolaruntime --debug`?

**Comment by a-m-s** [comment] 2018-04-24 10:41
Oops: 
[log.txt](https://github.com/tiliado/nuvolaruntime/files/1942345/log.txt)

**Comment by fenryxo** [comment] 2018-04-24 11:48
This is the log of the broken naviation request: `
CefEngine.vala:576: Navigation: new window false → false, uri = 'https://www.youtube.com/watch?v=_MoZS9p7Wdo&list=PLwx8_TBZ6z_md7Uj78vxYyljqKOwpEp6e&index=1%20', approved = false, frame = (null), type = TT_CLIENT_REDIRECT_FLAG, user gesture false`

I'm a bit puzzled as the "Science Museum" seems to be a normal link element `<a href="...">`, but it emits navigation request of type TT_CLIENT_REDIRECT_FLAG & "user gesture false". That's why the result of navigation decision (approved = false) is ignored ([source](https://github.com/tiliado/nuvolaruntime/blob/master/src/nuvolakit-runner/cef/CefEngine.vala#L590)). Normally, link navigations have "user gesture true" and "TransitionType.LINK". Maybe the link click is canceled by a JavaScript handler and replaced with `window.location.href = ...`. That might result in TT_CLIENT_REDIRECT_FLAG, but I need to verify it.

**Comment by a-m-s** [comment] 2018-04-24 12:09
If it's too hard to fix then don't bother; most BBC pages don't have (obvious) external links (not even advertising, when viewed from the UK).

This is just the first one that I found, clicking around. I'm not aware of it's being special, but if it opens inline then so be it.

**Comment by a-m-s** [comment] 2018-04-24 21:43
The YouTube page no longer opens in Nuvola. However, I get three copies of it in the browser.

Another observed oddity: if the saved page, reloaded at startup, is not allowed (this should only be able to happen after a metadata update) it's not possible to get back to a working state. Pressing the home button causes the page to load externally. The saved page is not updated, so there's no way out. Entering a URL manually has the same effect. In the end I removed the filter from the metadata, restarted, changed the saved page to the home page, reinstated the filter, restarted, and I'm back to usable again.

**Comment by fenryxo** [comment] 2018-04-25 18:43
How about eu.tiliado.NuvolaAdk//master Revision 34-ga372b81?

**Comment by fenryxo** [comment] 2018-04-26 07:09
We will hope that the issue is solved. If anything odd happens again, please always capture a debugging log.

I'll close this ticket once I rebuild stable flatpaks.

**Closed** 2018-04-30 11:27 UTC
Labels: bug
