### ISSUE TITLE
YouTube app doesn't Sign in and doesn't play videos (an error occured, please try again latter)

### ISSUE THREAD

**Issue by coldscientist** [tiliado/nuvolaruntime#361] opened 2017-07-16 22:14 UTC
Hello Guys,

Steps to reproduce the issue:

1. Open Nuvola Player YouTube app.
2. On the top right, click on "Sign in"
3. Type your e-mail and password.

After realizing Sign On, it starts on a Loop. When you close the app, you can read the following message on screen:

)]}'

[["er",null,null,null,null,405,null,null,null,9]
]

I had to remove manually the dir ~/.config/nuvolaplayer3/apps_data/youtube to restore the YouTube app.

When you try to play any video (without sign in), it shows the following message:

``An error occurred, please try again latter.``

I'm using Deepin 15.4 x86_64 (based on Debian Sid "Unstable") and installed it from official Tiliato repo (``deb https://tiliado.eu/nuvolaplayer/repository/deb/ sid stable``)

``$ lsb_release -a
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.4.1
Release:	15.4.1
Codename:	unstable``

``$ uname -m
x86_64``

``$nuvolaplayer3 --version
Nuvola Player 3 3.0.8
Revision 683fc7254443f13a35e4ba33d948ca6e382e690f
WebKitGTK 2.14.5
libsoup 2.56.0``

Debugging Output
Video tried to open (without sign in): https://www.youtube.com/watch?v=JGwWNGJdvx8&list=TLGG3DnPUKZUodwxNjA3MjAxNw&index=1 (Ed Sheeran - Shape of You)
``$ nuvolaplayer3 --debug
Master: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: mutter(deepingala) (null), CSD 0, appmenu 0, menubar 0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.5
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SiriusXM at /usr/share/nuvolaplayer3/web_apps/siriusxm, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.4
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app YouTube at /usr/share/nuvolaplayer3/web_apps/youtube, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.4
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.18
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 3.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebApp.vala:210: Theme icon nuvolaplayer3_test 48 not found.
Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.5
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SiriusXM at /usr/share/nuvolaplayer3/web_apps/siriusxm, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.4
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app YouTube at /usr/share/nuvolaplayer3/web_apps/youtube, version 1.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.4
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.18
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 3.2
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app YouTube, version 1.3, data dir /usr/share/nuvolaplayer3/web_apps/youtube
Master: [DEBUG    Nuvola] MasterController.vala:378: Launch app runner for 'youtube': /usr/lib/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/youtube 
Runner: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: mutter(deepingala) (null), CSD 0, appmenu 0, menubar 0
Runner: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] MasterController.vala:284: Connected to runner server for 'youtube'.
Runner: [DEBUG    Nuvola] config.vala:174: Json Error: Falha ao abrir arquivo "/home/eduardo/.config/nuvolaplayer3/apps_data/youtube/config.json": Arquivo ou diretório não encontrado
Runner: [DEBUG    Nuvola] Connection.vala:132: Network Proxy: system settings
Runner: [DEBUG    Nuvola] WebEngine.vala:73: Nuvola WebKit Extension directory: /usr/lib/nuvolaplayer3
Runner: [WARNING  DioriteGtk] actionsregistry.vala:170: Action 'donate' not found in registry.
Runner: [DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence false, actions false, icons false
Master: [DEBUG    Nuvola] MediaKeys.vala:134: GNOME settings daemon vanished: org.gnome.SettingsDaemon
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component tray_icon (Tray Icon) not enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component notifications (Notifications) enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component mediakeys (Media keys) enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component scrobbler (Audio Scrobbler Services) enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component mpris (MPRIS 2) enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component lyrics (Lyrics) enabled
Runner: [DEBUG    Nuvola] AppRunnerController.vala:416: Component developer (Developer's tools) enabled
Runner: [DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppYoutube, registering objects
Runner: [DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppYoutube
Worker: [DEBUG    Nuvola] WebExtension.vala:203: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:212: Document loaded about:loading
Runner: [DEBUG    Nuvola] WebEngine.vala:496: Navigation, current window: uri = https://www.youtube.com/feed/music, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 955
Runner: [INFO     Nuvola] config.vala:260: Config saved to /home/eduardo/.config/nuvolaplayer3/apps_data/youtube/config.json
Worker: [DEBUG    Nuvola] WebExtension.vala:113: Window object cleared for 'https://www.youtube.com/feed/music'
Worker: [DEBUG    Nuvola] WebExtension.vala:123: Init frame: https://www.youtube.com/feed/music, 0x56045d1f9a50, 0x56045ce0e720, 0x7f2a35bd40e0
Runner: https://www.youtube.com/feed/music:34:107: CONSOLE ERROR Failed to set referrer policy: The value 'origin-when-cross-origin' is not one of 'no-referrer', 'origin', 'no-referrer-when-downgrade', or 'unsafe-url'. Defaulting to 'no-referrer'.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from NULL to READY.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from PAUSED to PLAYING.
Worker: [DEBUG    Nuvola] WebExtension.vala:212: Document loaded https://www.youtube.com/feed/music
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /usr/lib/mozilla/plugins/flashplugin-alternative.so: Shockwave Flash 26.0 r0
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: IcedTea-Web Plugin (using IcedTea-Web 1.6.2 (1.6.2-3.1)) (enabled, not flash) at /usr/lib/mozilla/plugins/libjavaplugin.so: The <a href="http://icedtea.classpath.org/wiki/IcedTea-Web">IcedTea-Web Plugin</a> executes Java applets.
Runner: file:///usr/share/nuvolaplayer3/web_apps/youtube/integrate.js:122:24: CONSOLE LOG YouTube API connection error: TypeError: window.yt.player.getPlayerByElement is not a function. (In 'window.yt.player.getPlayerByElement('player-api')', 'window.yt.player.getPlayerByElement' is undefined)
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [INFO     Nuvola] config.vala:260: Config saved to /home/eduardo/.config/nuvolaplayer3/apps_data/youtube/config.json
Runner: libva info: VA-API version 0.39.4
Runner: libva info: va_getDriverName() returns 0
Runner: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
Runner: libva info: Found init function __vaDriverInit_0_39
Runner: libva info: va_openDriver() returns 0
Runner: libva info: VA-API version 0.39.4
Runner: libva info: va_getDriverName() returns 0
Runner: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
Runner: libva info: Found init function __vaDriverInit_0_39
Runner: libva info: va_openDriver() returns 0
Runner: [INFO     Nuvola] config.vala:260: Config saved to /home/eduardo/.config/nuvolaplayer3/apps_data/youtube/config.json
Runner: [DEBUG    Nuvola] WebEngine.vala:496: Navigation, current window: uri = https://googleads.g.doubleclick.net/pagead/ads?ad_block=2&client=ca-pub-6219811747049371&format=300x250_as&output=html&h=250&w=300&loeid=9419451%2C9422596%2C9431012%2C9434289%2C9441391%2C9451823%2C9457019%2C9460350%2C9462695%2C9465813%2C9474356%2C9475698%2C9477113%2C9477535%2C9478418%2C9478738%2C9478839%2C9480539%2C9480648%2C9480776%2C9481951%2C9482289%2C9482503%2C9482851%2C9483014&pucrd=CgYIABAAGAA&channel=0854550287%2BVertical_1021%2BVertical_1027%2BVertical_1408%2BVertical_211%2BVertical_36%2BVertical_613%2BVertical_617%2Bafc_on_page%2Bafv_user_edsheeran%2Bafv_user_id_0C-w0YjGpqDXGB8IHb662A%2Byt_cid_1%2Byt_gp%2Byt_mpvid_TkBdF52EBj86wZSB%2Byt_no_ap%2Byt_no_cp%2Byt_no_wa%2Bytdevice_1%2Bytdevicever_1.20170712%2Bytel_detailpage%2Bytps_default&host=ca-host-pub-9338557111912616&ht_id=4326035&ad_type=image&alternate_ad_url=https%3A%2F%2Fwww.youtube.com%2Fad_frame%3Fid%3Dwatch-channel-brand-div&flash=26.0.0&hl=pt&url=http%3A%2F%2Fwww.youtube.com%2Fvideo%2FJGwWNGJdvx8&video_doc_id=yt_JGwWNGJdvx8&wgl=1&dbp=ChZYbld4ZC0yRDJMSU81RmszdTZrcU1REAEgASgA&lact=-1&yt_pt=APb3F2_axkakcC4gwB9_x2Ez7CffTjHiVLVpzEDz_shIjti-MG4Pei_QZGHtcT6gMVasEX57kgPaTQkcq2IdZf0uW5aS7JB0DP670BHJKmRTG56P1BcwatXeG5jo5EHiB9YkQKb2ZHkDG9HzVUHo&dt=1500242575657&bdt=9585&idt=0&shv=r20100101&cbv=r20100101&correlator=4824247308847&frm=20&ga_vid=81929664.1500242576&ga_sid=1500242576&ga_hid=453543529&ga_fc=0&pv=2&iag=0&icsg=200293519&dssz=24&mdo=0&mso=0&u_tz=-180&u_his=2&u_java=0&u_h=768&u_w=1366&u_ah=768&u_aw=1366&u_cd=24&u_nplug=2&u_nmime=148&biw=1100&bih=559&loc=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJGwWNGJdvx8%26list%3DTLGG3DnPUKZUodwxNjA3MjAxNw&rx=0&brdim=50%2C50%2C50%2C50%2C1366%2C0%2C1100%2C600%2C1100%2C559&vis=1&ppjl=u&pfx=0&fu=4096&bc=1&js=uds&eid=37464000, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: libva info: VA-API version 0.39.4
Runner: libva info: va_getDriverName() returns 0
Runner: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
Runner: libva info: Found init function __vaDriverInit_0_39
Runner: libva info: va_openDriver() returns 0``

**Comment by fenryxo** [comment] 2017-07-17 08:21
Hello @coldscientist. No need to report the same issue three times. Closing as a duplicate of https://groups.google.com/d/msg/nuvola-player-users/_28EEAQNGA0/5zklBvW9BwAJ

**Closed by fenryxo** 2017-07-17 08:21 UTC
