### ISSUE TITLE
Youtube Music Stopped Working

### ISSUE THREAD

**Issue by vedanshgarg** [tiliado/nuvolaruntime#517] opened 2019-05-05 08:09 UTC
Since 2 days, Youtube Music is not working. Instead, its showing error "Oops Something went wrong".

---

### Basic information

- Your Linux distribution and its version: Elementary OS 5.0 Juno

- Your desktop environment: Patheon (default in elementaryOS),

 - Nuvola Runtime version: 4.16.4 (4-g819cdb2)

 - The web app you use and its version: Youtube Music ( 1.3.0 (0-gbbf30d7) )

### Describe the bug

Youtube Music is not working. Instead, its showing error "Oops Something went wrong".

**Steps to reproduce the behavior**

Just open the app or try to reload or sign in.

**Expected behavior**

...

**Debugging log**
[dubug.txt](https://github.com/tiliado/nuvolaruntime/files/3145418/dubug.txt)

**Screenshots**
![Screenshot from 2019-05-05 15-54-53](https://user-images.githubusercontent.com/40305225/57192555-66d75b80-6f4f-11e9-9de6-985e7709341a.png)

**Comment by fenryxo** [comment] 2019-05-05 10:18
Hello @vedanshgarg. Thanks for reporting the issue. I've updated your report with a bug reporting template. Could you edit your report and fill in missing fields? That would make bug triaging faster. Thanks.

To edit your post, click the three dots in the top right corner of your post and select Edit.

**Comment by vedanshgarg** [comment] 2019-05-05 10:36
info updated

**Comment by fenryxo** [comment] 2019-05-12 13:37
Thanks, @vedanshgarg. I apologize for the late response.  I've been moving to a new flat so life is a bit crazy nowadays.

I'm now in a process of upgrading Nuvola's embedded Chromium to the latest version. The build was successful and I'm going to test it next week. Thanks for your patience.

**Comment by fenryxo** [comment] 2019-05-12 13:38
I hope that the upgraded Chromium will resolve the issue.

**Comment by vedanshgarg** [comment] 2019-05-17 21:52
Great, Looking forward to the new build.

**Comment by fenryxo** [comment] 2019-06-01 17:19
Hello @vedanshgarg. I'm afraid I cannot reproduce the issue with Nuvola stable (Chromium 73) nor Nuvola devel (Chromium 74). Could you try removing the cache with this command and see whether it helps?

```
rm -rf ~/.var/app/eu.tiliado.NuvolaAppYoutubeMusic/{cache,data}
```

**Comment by fenryxo** [comment] 2019-09-15 11:23
Closing this ticket as there hasn't been any response since June 1st.

**Closed by fenryxo** 2019-09-15 11:23 UTC
Labels: need info, type: bug
