### ISSUE TITLE
Google "Couldn't sign you in"

### ISSUE THREAD

**Issue by sk8darr** [tiliado/nuvolaruntime#579] opened 2020-01-29 17:50 UTC
### Basic information

- Your Linux distribution and its version: Ubuntu 19.10

- Your desktop environment: GNOME 3.34.1 (Default)

 - Nuvola Runtime version: 4.16.22 (22-g1bf660b)

 - The web app you use and its version: YouTube Music Script 1.3.2 (2-g44bacab)

### Describe the bug
Can't signin to my account

**Steps to reproduce the behavior**

1.- Clean installation using the latest version
2.- Open de app
3.- Click Login / Signin
4.- Try to sign with your google account
5.- Google sign show a message: "Couldn't sign you in"

**Expected behavior**

Sign success

**Debugging log**

Attach the debug log here: [log_debug.txt](https://github.com/tiliado/nuvolaruntime/files/4129618/log_debug.txt)

**Screenshots**

Attach screenshots here: ![Captura de pantalla de 2020-01-29 11-46-57](https://user-images.githubusercontent.com/1724673/73382581-632df680-428d-11ea-91f0-6621250735e9.png)

**Comment by K4S1** [comment] 2020-01-30 08:56
100% same symptoms here

```
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```
"Learn more" link pointing to:
https://support.google.com/accounts/answer/7675428?hl=en

**Comment by fenryxo** [comment] 2020-02-02 13:15
Hello. This is a duplicate of #575. I'm having trouble to upgrade Chromium to anything newer than 75 :-( Networking doesn't work.

**Closed by fenryxo** 2020-02-02 13:15 UTC
Labels: duplicate
