### ISSUE TITLE
Deezer without sounds

### ISSUE THREAD

**Issue by servicomf5** [tiliado/nuvolaruntime#525] opened 2019-05-25 18:33 UTC
i get this error when run Deezer

```
# flatpak run eu.tiliado.NuvolaAppDeezer

Note that the directory 

'/root/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.


** (process:5913): WARNING **: Error writing credentials to socket: Error sending message: Broken pipe
Runner: [WARNING Δ152142us Nuvola] AppRunnerController.vala:250: GTK+ theme 'Xfce' does not exist, using Greybird theme instead.
Runner: [CRITICAL Δ01s499005us DioriteGtk] drtgtk_application_on_xfce_session_vanished: assertion 'conn != NULL' failed
Runner: [CRITICAL Δ000054us DioriteGtk] Application will not function properly.
Runner: [WARNING Δ372150us Nuvola] StartupWindow.vala:146: xdg-desktop-portal-message: La conexión está cerrada
```
Please your help
Debian 9.9 (stretch)

**Comment by fenryxo** [comment] 2019-05-25 20:50
Hello @servicomf5. Running Nuvola as the root user is not supported. Does Nuvola work if you run it as a regular user?

**Comment by servicomf5** [comment] 2019-05-26 01:28
> Hello @servicomf5. Running Nuvola as the root user is not supported. Does Nuvola work if you run it as a regular user?

Hi, I started it as a user without root privileges but it still does not emit Deezer sound.
This is the terminal log.

```
$ flatpak run eu.tiliado.NuvolaAppDeezer
Runner: [WARNING Δ468480us Nuvola] StartupWindow.vala:146: nuvola-service-message: Failed to connect to Nuvola Apps Service, but it is optional.

<i>Error message: Failed to get Nuvola Service version. GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name eu.tiliado.Nuvola was not provided by any .service files</i>
Runner: [WARNING Δ000375us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: Free

(eu.tiliado.NuvolaAppDeezer:3): Gtk-WARNING **: 21:21:17.923: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. http://code.google.com/p/chromium/issues/detail?id=16800
[0525/212142.841089:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
Worker: [DEBUG Δ013163us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ000072us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Falló al abrir la carpeta «/usr/share/gvfs/remote-volume-monitors»: No existe el fichero o el directorio
Worker: [DEBUG Δ001559us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [CRITICAL Δ25s095818us Nuvola] file src/nuvolakit-runner/AudioTweaksComponent.c: line 372: uncaught error: 6: Conexión negada pa_context_connect() failed. (nuvola-audio-error-quark, 0)
Runner: [CRITICAL Δ000064us Nuvola] Application will not function properly.
Runner: [WARNING Δ000037us Nuvola] Component.vala:137: Failed to activate: audio_tweaks Audio Tweaks
Worker: [DEBUG Δ035113us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ000049us CefGtk] RendererContext.vala:57: JS Context created 1
[0526/012143.208533:ERROR:browser_main_loop.cc(279)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Worker: [DEBUG Δ012875us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ000077us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Falló al abrir la carpeta «/usr/share/gvfs/remote-volume-monitors»: No existe el fichero o el directorio
Worker: [DEBUG Δ001714us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ008839us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ006079us CefGtk] RendererContext.vala:57: JS Context created 1
Worker: [DEBUG Δ664248us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000063us CefGtk] RendererContext.vala:64: JS Context released: 1
[0526/012144.061853:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
[0526/012144.063350:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
[0526/012144.845573:WARNING:leveldb_database.cc(111)] Unable to open /home/eduardo/.var/app/eu.tiliado.NuvolaAppDeezer/data/nuvolaruntime/apps_data/deezer/cef: IO error: /home/eduardo/.var/app/eu.tiliado.NuvolaAppDeezer/data/nuvolaruntime/apps_data/deezer/cef/LOCK: Lock file already locked. (ChromeMethodOnly: 15::LockFile)
[0526/012144.846475:WARNING:leveldb_database.cc(314)] Unable to destroy /home/eduardo/.var/app/eu.tiliado.NuvolaAppDeezer/data/nuvolaruntime/apps_data/deezer/cef: IO error: /home/eduardo/.var/app/eu.tiliado.NuvolaAppDeezer/data/nuvolaruntime/apps_data/deezer/cef/LOCK: Lock file already locked. (ChromeMethodOnly: 15::LockFile)
[0526/012145.372327:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012145.372381:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012145.683303:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012145.683425:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[0526/012154.992882:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012154.993063:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
ALSA lib ../../pulse/pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión negada

[0526/012155.005187:ERROR:alsa_util.cc(204)] PcmOpen: default,Conexión rehusada
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_plug_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_plug_open is not defined inside [builtin]
[0526/012155.005356:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No existe el dispositivo o la dirección
[0526/012155.049872:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012155.049912:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[0526/012155.290218:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012155.290315:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012207.195311:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012207.195455:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012207.249409:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012207.249859:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
Worker: [DEBUG Δ02m47s936322us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000231us CefGtk] RendererContext.vala:64: JS Context released: 1
Worker: [DEBUG Δ006157us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ007251us CefGtk] RendererContext.vala:57: JS Context created 1
[0526/012431.760484:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
[0526/012431.762827:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
[0526/012432.835699:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012432.835735:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012432.888611:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012432.888773:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[0526/012433.363655:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012433.363747:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012433.403340:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012433.403437:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[0526/012433.641714:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012433.641830:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
[0526/012443.526304:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012443.526441:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
[0526/012443.802231:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.UnInhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012443.802276:ERROR:power_save_blocker_x11.cc(403)] No response to Uninhibit() request!
ALSA lib ../../pulse/pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión negada

[0526/012444.253128:ERROR:alsa_util.cc(204)] PcmOpen: default,Conexión rehusada
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_plug_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_plug_open is not defined inside [builtin]
[0526/012444.253324:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No existe el dispositivo o la dirección
[0526/012444.676476:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0526/012444.676631:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
```

**Comment by fenryxo** [comment] 2019-05-27 10:19
Probably unrelated, but there is something wrong with the `~/.var/app/eu.tiliado.NuvolaAppDeezer` directory. Could you delete it?

```
sudo rm -rf /home/eduardo/.var/app/eu.tiliado.NuvolaAppDeezer
```

There are several audio-related errors:

```
ALSA lib ../../pulse/pulse.c:243:(pulse_connect) PulseAudio:
Unable to connect: Conexión negada (Connection denied)
[0526/012155.005187:ERROR:alsa_util.cc(204)] PcmOpen:
default,Conexión rehusada (Connection refused)
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_plug_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_plug_open is not defined inside [builtin]
[0526/012155.005356:ERROR:alsa_util.cc(204)] PcmOpen:
plug:default,No existe el dispositivo o la dirección (There is no device or address)
```

However, I cannot reproduce them on a fresh Debian Stretch GNOME installation. I need to learn how Flatpak apps connect to PulseAudio and I'll ask more questions afterward.

**Comment by servicomf5** [comment] 2019-05-27 17:41
I'll wait for your answer
Rgds,

**Comment by fenryxo** [comment] 2019-06-30 16:53
Hello @servicomf5.  I apologize for the late response. I've finished moving to a new flat this week, so I finally have some spare time to work on Nuvola.

Could you post the output of the following command?

```
$ flatpak run --command=env eu.tiliado.NuvolaAppDeezer | grep PULSE
PULSE_SERVER=unix:/run/user/1000/pulse/native
PULSE_CLIENTCONFIG=/run/user/1000/pulse/config
```

**Comment by servicomf5** [comment] 2019-06-30 16:56
Don't you worry, i had to reinstall Ubuntu instead Debian and this and
other issues we're solved.

Rgds,

EM

**Comment by fenryxo** [comment] 2019-06-30 19:30
Ok, glad to hear you managed to solve the issue on your own.

**Closed by fenryxo** 2019-06-30 19:30 UTC
Labels: need info, status: in progress, type: bug
