### ISSUE TITLE
Cannot login to BBC site via iPlayer script

### ISSUE THREAD

**Issue by markcross** [tiliado/nuvolaruntime#476] opened 2018-09-28 21:31 UTC
BBC iPlayer script 1.5 
ubuntu/xenial/

On clicking on Sign-in, it fires up my default browser, FireFox then takes me to:

https://account.bbc.com/account/error

metadata.json line:

  "allowed_uri": "^https?://[^/]*.bbc.co.uk",

Needs to allow both *.bbc.co.uk and *.bbc.com as the BBC are now using the .com for their ID authentication.

Works with:

  "allowed_uri": "^https?://[^/]*.bbc.*",

But I have no idea if this is the correct fix....

Cheers Mark

**Comment by fenryxo** [comment] 2018-09-29 07:53
Hello @markcross, thanks for reporting this issue.

Hello @a-m-s, could you look at this? Thanks.

**Comment by a-m-s** [comment] 2018-09-29 08:15
Did you release the latest update yet?

I think that should do it, but I can't check now.

**Comment by fenryxo** [comment] 2018-09-29 08:29
@markcross, do you use BBC iPlayer script 1.5.0 or 1.5.7? You can get the exact version from About dialog?

@a-m-s, the latest master was released but it still contains `"allowed_uri": "^https?://[^/]*.bbc.co.uk"` so `bbc.com` is not allowed.

**Comment by a-m-s** [comment] 2018-09-30 21:31
Oh, I fixed a problem with the machine name, but I didn't see an issue with
the TLD.

Ok, I'll sort it tomorrow, probably.

**Comment by a-m-s** [comment] 2018-10-01 14:03
Should be fixed now (pending release).

**Comment by fenryxo** [comment] 2018-10-02 08:10
Updated flatpaks published.

@markcross, could you update BBC iPlayer script to 1.5.9 (9-g5fb2022) and confirm thath the issue is resolved?

**Comment by fenryxo** [comment] 2018-10-15 07:57
[Released in Nuvola 4.13.0 & BBC iPlayer 1.6](https://medium.com/nuvola-news/nuvola-4-13-released-2fdf80c73742).

**Closed by fenryxo** 2018-10-15 07:57 UTC
Labels: need info, status: to release, type: bug
