### ISSUE TITLE
Unable to start Nuvola Runtime (KDE Neon, Ubuntu Artful, Wayland)

### ISSUE THREAD

**Issue by Evpok** [tiliado/nuvolaruntime#390] opened 2017-10-23 08:02 UTC
Running 

```bash
$ flatpak run eu.tiliado.Nuvola --debug

(eu.tiliado.Nuvola:2): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Master: [DEBUG Δ021867us Nuvola] XKeyGrabber.vala:190: Obtained a X11 Window for the display ':99.0'.
Master: [DEBUG Δ054462us DioriteGtk] DesktopShell.vala:152: Shell: kwin (null), CSD 0, appmenu 0, menubar 0
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Master: [DEBUG Δ048109us DioriteGtk] Application.vala:265: XFCE session vanished: org.xfce.SessionManager
```

And shows the following message
![image](https://user-images.githubusercontent.com/1656541/31877094-776a0098-b7d5-11e7-9818-789788cddb25.png)

Also (where I first saw the issue)

```bash
$ flatpak run eu.tiliado.NuvolaAppDeezer

(nuvola-app-deezer:2): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Runner: [WARNING Δ206156us Nuvola] StartupWindow.vala:183: xdg-desktop-portal-message: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.freedesktop.portal.Desktop received signal 11
```

![image](https://user-images.githubusercontent.com/1656541/31877192-d6f9ec44-b7d5-11e7-80dc-0d075aa7c720.png)

## System
Running a Plasma Wayland session in KDE Neon over Ubuntu Artful

```bash
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:         17.10
Codename:     artful
$ uname -m
x86_64
$ flatpak run eu.tiliado.Nuvola --version   
Nuvola Apps - Genuine flatpak build
Version 4.8.24
Revision 24-g054ab56
Diorite 4.8.6
WebKitGTK 2.18.1
libsoup 2.58.2
```

**Comment by fenryxo** [comment] 2017-10-23 08:43
Hello @Evpok.

> `xdg-desktop-portal-message: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.freedesktop.portal.Desktop received signal 11`

I saw this error message with `xdg-desktop-portal-kde`. Does your distro provide `xdg-desktop-portal-gtk`?

**Comment by Evpok** [comment] 2017-10-23 08:51
Yes, but I have `xdg-desktop-portal-kde` installed too, can't both be used together ?

Also I tried using the Plasma over X instead of Wayland and everything seems to work fine

**Comment by fenryxo** [comment] 2017-10-23 08:58
I'll look at it further but until the issue is resolved, I recommend uninstalling `xdg-desktop-portal-kde` because it crashes.

**Comment by fenryxo** [comment] 2017-12-16 17:15
The same issue is in OpenSUSE 42.3. [I've filled a bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1073194).

If you can reproduce following failing dbus-send call with xdg-desktop-portal-kde in KDE Neon, please create a bug report as well.

```
$ dbus-send --print-reply --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.ProxyResolver.Lookup string:"http://google.com" 
Error org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.freedesktop.portal.Desktop received signal 11
```

**Comment by fenryxo** [comment] 2018-01-02 13:52
Closing as an upstream issue. Fixed by this commit https://github.com/KDE/xdg-desktop-portal-kde/commit/71a26013b409ddce0af66e6d0a04a45ff4f1bbcb

**Closed by fenryxo** 2018-01-02 13:52 UTC
Labels: bug
