### ISSUE TITLE
Nvidia 396.24.02 OpenGL Driver Error

### ISSUE THREAD

**Issue by CodrinE** [tiliado/nuvolaruntime#443] opened 2018-06-13 09:46 UTC
**Blocked by:** flatpak/flatpak#1786

Workaround
----------------

Use the `FLATPAK_GL_DRIVERS=nvidia-396-24` environment variable for now, e.g.

```
FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run eu.tiliado.NuvolaAppDeezer
```

Issue
-------

* `cat /sys/module/nvidia/version` → 396.24.02
* `flatpak --version` → Flatpak 0.11.7

```
$ flatpak remote-list --show-details | grep flathub
flathub	Flathub	https://dl.flathub.org/repo/	1	system
$ flatpak remote-ls flathub | grep nvidia
org.freedesktop.Platform.GL.nvidia-396-24
```

I have already issued **flatpak update** and installed: `flatpak install flathub org.freedesktop.Platform.GL.nvidia-396-24`, but I still get the next error:

```
$ flatpak run eu.tiliado.NuvolaAppDeezer
Runner: [WARNING Δ231809us Nuvola] StartupWindow.vala:205: opengl-driver-message: Graphics driver 'nvidia-396-24-02' for Flatpak has not been found on your system. Please consult <a href="https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers">documentation on graphics drivers</a> to get help with installation.
```

**Comment by fenryxo** [comment] 2018-06-13 09:55
Hello @CodrinE. Thanks for reporting this issue. It seems that Nvidia started reporting the third version number (`396.24.02` instead of `396.24`) and Nuvola became confused.

**Comment by fenryxo** [comment] 2018-06-13 10:13
Fix committed to master branch but I won't be able to rebuild flatpaks until tomorrow.

**Comment by CodrinE** [comment] 2018-06-13 10:19
Thank you for your help **@fenryxo**.
Hope it gets fixed soon so I can try and see if it works.

**Comment by fenryxo** [comment] 2018-06-14 10:47
Could you check that it works with Nuvola 4.11.30? (You can check the version with e.g. `flatpak run eu.tiliado.NuvolaAppDeezer --version`.)

**Comment by CodrinE** [comment] 2018-06-14 13:19
It does not seem to work at the moment:

$ flatpak run eu.tiliado.NuvolaAppDeezer --version
Deezer script
Version: 3.0.9
Revision: 9-g30dcb32
Maintainer: Jiří Janoušek

--- Powered by ---

Nuvola Apps - Genuine flatpak build
Version 4.11.30
Revision 30-gd13e08a
Diorite 4.11.2
WebKitGTK 2.20.2
Chromium 67.0.3396.79
libsoup 2.62.1

**Comment by fenryxo** [comment] 2018-06-14 13:56
Could you attach [a debugging output](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output)?

**Comment by CodrinE** [comment] 2018-06-14 14:15
This is what I get when running it in debug mode:

flatpak run eu.tiliado.NuvolaAppDeezer --debug
Runner: [DEBUG Δ041192us Nuvola] AboutDialog.vala:54: Nuvola Apps 4.11.30 (30-gd13e08a)
Runner: [DEBUG Δ000046us Nuvola] AboutDialog.vala:56: Deezer script 3.0.9 (9-g30dcb32)
Runner: [DEBUG Δ000016us Nuvola] AboutDialog.vala:60: Diorite 4.11.2
Runner: [DEBUG Δ000108us Nuvola] AboutDialog.vala:62: Chromium 67.0.3396.79
Runner: [DEBUG Δ002146us DioriteGtk] DesktopShell.vala:251: Shell: gnome shell 3.28.1, CSD 1, appmenu 0, menubar 0
Runner: [DEBUG Δ000541us Nuvola] Connection.vala:115: Network Proxy: system settings
Runner: [DEBUG Δ000820us Nuvola] WebkitOptions.vala:51: MSE supported: no
Runner: [DEBUG Δ181839us Nuvola] AppRunnerController.vala:114: Scale factor: 1
Runner: [DEBUG Δ000161us Nuvola] Gstreamer.vala:45: Nuvola GStreamer cache tag does not exist. /home/code/.var/app/eu.tiliado.NuvolaAppDeezer/cache/gstreamer-1.0/__nuvola_4_11_30__
Runner: [DEBUG Δ399960us Nuvola] FormatSupport.vala:86: Trying to play /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ001346us DioriteGtk] Application.vala:276: XFCE session vanished: org.xfce.SessionManager
Runner: [DEBUG Δ000167us Nuvola] FormatSupport.vala:86: Pipeline state changed from NULL to READY.
Runner: [DEBUG Δ000301us Nuvola] Graphics.vala:35: Nvidia 396.24.02, i915 0, bumblebeed 0 => ignored 0
Runner: [WARNING Δ000099us Nuvola] StartupWindow.vala:205: opengl-driver-message: Graphics driver 'nvidia-396-24' for Flatpak has not been found on your system. Please consult <a href="https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers">documentation on graphics drivers</a> to get help with installation.
Runner: [DEBUG Δ008710us Nuvola] FormatSupport.vala:86: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG Δ000104us Nuvola] FormatSupport.vala:86: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG Δ019253us Nuvola] FormatSupport.vala:86: End of stream for file /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ003243us Nuvola] StartupCheck.vala:216: Checking requirements with WebKitGTK 2.20.2
Runner: [DEBUG Δ000081us Nuvola] Traits.vala:62: Chromium[63] -> DRT_REQUIREMENT_STATE_UNSUPPORTED 
Runner: [DEBUG Δ000028us Nuvola] Traits.vala:62: Feature[MSE] -> DRT_REQUIREMENT_STATE_UNSUPPORTED 
Runner: [DEBUG Δ000054us Nuvola] StartupCheck.vala:216: Checking requirements with Chromium 67.0.3396.79
Runner: [DEBUG Δ000028us Nuvola] Traits.vala:62: Chromium[63] -> DRT_REQUIREMENT_STATE_SUPPORTED 
Runner: [DEBUG Δ000054us Nuvola] Traits.vala:62: Feature[MSE] -> DRT_REQUIREMENT_STATE_SUPPORTED

**Comment by CodrinE** [comment] 2018-06-14 14:19
[NuvolaAppDeezer debugging output.txt](https://github.com/tiliado/nuvolaruntime/files/2102681/NuvolaAppDeezer.debugging.output.txt)

**Comment by CodrinE** [comment] 2018-06-14 14:37
Just noticed after that I could upload the file.

ls /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-396-24/x86_64/1.4/active/
deploy  files  metadata

flatpak run --command=ls eu.tiliado.NuvolaAppDeezer /usr/lib/GL
glvnd  OpenCL  vulkan

**Comment by fenryxo** [comment] 2018-06-14 14:41
* What does `FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run --command=ls eu.tiliado.NuvolaAppDeezer /usr/lib/GL` say?

* Could you attach the output of `FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run --command=ls eu.tiliado.NuvolaAppDeezer --debug` and check whether Deezer starts?

**Comment by CodrinE** [comment] 2018-06-14 15:06
The first command just displays:
glvnd  nvidia-396-24  vulkan

Second command gives me an error 
ls: unrecognized option '--debug'
Try 'ls --help' for more information.

I have also done the next command which seems to be starting the app:
FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run eu.tiliado.NuvolaAppDeezer --debug

Output here:
[output_b.txt](https://github.com/tiliado/nuvolaruntime/files/2102876/output_b.txt)

**Comment by fenryxo** [comment] 2018-06-14 15:34
> Second command gives me an error
> ls: unrecognized option '--debug'
> Try 'ls --help' for more information.

Sorry, I forgot to remove `--command=ls`, but I'm glad you managed to run the correct command anyway :+1: 

The problem is that flatpak expects the extension to be named `org.freedesktop.Platform.GL.nvidia-396-24-02` (to match `396.24.02` from `/sys/module/nvidia/version`), so `org.freedesktop.Platform.GL.nvidia-396-24` is not mounted until you force in with `FLATPAK_GL_DRIVERS=nvidia-396-24`. I've reported the issue as flatpak/flatpak#1786.

> I have also done the next command which seems to be starting the app:
> FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run eu.tiliado.NuvolaAppDeezer --debug

Good. You can use the `FLATPAK_GL_DRIVERS=nvidia-396-24` environment variable as a workaround for now.

**Comment by CodrinE** [comment] 2018-06-14 15:39
I will use this workaround for the time being.
Please let me know when this is fixed if possible.

**Comment by fenryxo** [comment] 2018-06-19 09:14
Hello @CodrinE. Could you follow flatpak/flatpak#1786 and reply to questions there? I don't have any Nvidia hardware so I cannot keep that ticket alive nor put it forward.

**Comment by fenryxo** [comment] 2018-07-23 12:57
Hello @CodrinE. I'm closing this ticket as abandoned because you forgot to participate in the discussion at flatpak/flatpak#1786. I've added a note at https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers#issues for other users that could bump into this issue.

**Closed by fenryxo** 2018-07-23 12:57 UTC
Labels: status: blocked, type: bug
