### ISSUE TITLE
Annoying white line between app window and web component

### ISSUE THREAD

**Issue by pedrofleck** [tiliado/nuvolaruntime#557] opened 2019-09-17 13:25 UTC
### Basic information

- Your Linux distribution and its version: Linux Mint 19.2
   

- Your desktop environment: Cinnamon
   

 - Nuvola Runtime version: 4.16.21
   

 - The web app you use and its version: YouTube Music 1.3.2
   

### Describe the bug

I don't know if this happens with other media players since I just use YouTube Music, but I have an annoying white line (I think it's 1px) just below the CSD, it is specially noticeable since my theme **and** the player are on dark tones. The expected behaviour would be not having this line, I think.

**Debugging log**

Attach the debug log here: [eu.tiliado.NuvolaAppYoutubeMusic debug.txt](https://github.com/tiliado/nuvolaruntime/files/3621475/eu.tiliado.NuvolaAppYoutubeMusic.debug.txt)

**Screenshots**

Attach screenshots here: 
![Captura de tela de 2019-09-17 10-14-40](https://user-images.githubusercontent.com/761321/65045513-5095cf00-d935-11e9-9e08-b538a3761200.png)

**Comment by fenryxo** [comment] 2019-09-21 09:09
Hello @pedrofleck. Thanks for reporting the issue. It's a duplicate of #436.

**Closed by fenryxo** 2019-09-21 09:09 UTC

**Comment by fenryxo** [comment] 2019-09-22 08:47
Until the issue is fixed - and it may take a while as I still have no idea what is the cause of it - you can choose a different theme in *Preferences* - *Appearance tweaks* (e.g. Adwaita, Greybird) and toggle on *Prefer a dark variant if the theme provides it*.
