### ISSUE TITLE
I am not able to use the Tidal application

### ISSUE THREAD

**Issue by schatderer** [tiliado/nuvolaruntime#595] opened 2020-03-30 15:55 UTC
I am trying to use the Tidal application, however, when I run the program (by the shortcut created on the Desktop or the 'flatpak run eu.tiliado.NuvolaAppTidal' command), I am faced with the Widevine plugin installation requirement. When I click to install such plugin, there is always an error message that prevents me from installing the application: 

 Error ocurred: Plugin not found in a file from 'https://-dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'.

Also, the error occurs because the URL is not correct, since a 'dash' (-) appears before 'dl.google.com'. That is, the correct URL would be 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', so this is an error in the application's script. Therefore, please correct this so that I can use the application.

---

Please select Edit from the triple dot menu and fill this template:

### Basic information

- Your Linux distribution and its version: Calculate Linux Scratch 20
   

- Your desktop environment: MATE
   

 - Nuvola Runtime version: 4.16.32 (32-gb6b0ee5)
   

 - The web app you use and its version: Tidal 1.0.3 (3-g72f3d2f)
   

### Describe the bug

When I run the program, the Widevine plugin must be installed. When I try to do this, I always come across a certain error message (attached image). This occurs because the URL to download the plugin is not correct: there is a dash (-) at the beginning of the address (after https://), thus making it invalid.

**Steps to reproduce the behavior**

1. I run the program (command 'flatpak run eu.tiliado.NuvolaAppTidal')
2. Click 'I accept Google Chrome End User License Agreement'
3. Click on 'Install plugin'
4. The error occurs

**Expected behavior**

The plugin should be installed normally if the URL address is correct.

**Debugging log**

Attach the debug log here: 
[Nuvola-Tidal-debug.txt](https://github.com/tiliado/nuvolaruntime/files/4411289/Nuvola-Tidal-debug.txt)

**Screenshots**

Attach screenshots here: 
![screen01](https://user-images.githubusercontent.com/62896446/78069634-f49f0f00-7389-11ea-9e66-0e964d16ba06.png)
![screen02](https://user-images.githubusercontent.com/62896446/78069690-08e30c00-738a-11ea-8c7b-c076c2886742.png)
![screen03](https://user-images.githubusercontent.com/62896446/78069701-0f718380-738a-11ea-8b06-2b18f5b99ce3.png)

**Additional context**

As mentioned earlier, the bug occurs because the program tries to download a file from a URL that does not exist (whose reason has already been identified).

**Comment by fenryxo** [comment] 2020-03-31 18:55
Hello @schatderer, I'm afraid I cannot reproduce your issue. I've updated your post with an issue template. Could select Edit from the triple dot menu and fill in the template? Thanks.

**Comment by fenryxo** [comment] 2020-04-05 09:48
Thanks, @schatderer. The URL used is actually correct (the log says `CefPluginDownloaderDialog.vala:116: NuvolaCefWidevineDownloader installation failed: Plugin not found in a file from 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'.`) but incorrectly displayed in the error dialog.

I've added more debugging information to Nuvola and will let you know once the flatpaks are rebuilt.

**Comment by fenryxo** [comment] 2020-04-05 11:04
Flatpaks published. Could you provide me with new debugging output with Nuvola 4.16.33 (33-gea8267a)?

**Comment by fenryxo** [comment] 2020-05-16 08:31
Closing as there are no new logs. Hopefully, it's because the issue is resolved.

**Comment by mirsemen** [comment] 2020-08-09 13:56
I have the same error.

**Basic information**
Your Linux distribution and its version: Calculate Linux Desktop 20.6
Your desktop environment: MATE
Nuvola Runtime version: 4.16.42 (42-g941fa66)
The web app you use and its version: Tidal 1.0.3 (3-g72f3d2f)

**Debug log**
[nuvola-tidal-debug.txt](https://github.com/tiliado/nuvolaruntime/files/5047625/nuvola-tidal-debug.txt)

**Comment by fenryxo** [comment] 2020-08-09 14:59
Hello @mirsemen. It looks as if the downloaded deb package was empty. I need to add the file size and hash to the debugging output to investigate it further.

**Comment by fenryxo** [comment] 2020-08-15 13:42
Help  @mirsemen, could you provide new log with Nuvola 4.16.43 (43-g7ccd3dd)?

**Comment by mirsemen** [comment] 2020-08-18 03:05
> Hello @mirsemen, could you provide new log with Nuvola 4.16.43 (43-g7ccd3dd)?

Hi, @fenryxo !

[tidal-flatpack-debug.txt](https://github.com/tiliado/nuvolaruntime/files/5087910/tidal-flatpack-debug.txt)

**Comment by fenryxo** [comment] 2020-08-23 18:43
Yes, the error is the same but there is more information in the logs. The downloaded file is indeed empty. I've found a bug that swallowed connection errors. Could you provide new log with Nuvola 4.16.44 (44-g4f7864a)? I hope to get more info about why the download fails.

**Comment by mirsemen** [comment] 2020-08-25 06:49
Here 

> Yes, the error is the same but there is more information in the logs. The downloaded file is indeed empty. I've found a bug that swallowed connection errors. Could you provide new log with Nuvola 4.16.44 (44-g4f7864a)? I hope to get more info about why the download fails.

Here u go!
[tidal-flatpack-debug-4.16.44.txt](https://github.com/tiliado/nuvolaruntime/files/5121793/tidal-flatpack-debug-4.16.44.txt)

**Comment by fenryxo** [comment] 2020-08-25 10:13
Could you try URL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb in your web browser to find out whether you get the certificate error too?

**Comment by mirsemen** [comment] 2020-08-25 10:16
> Could you try URL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb in your web browser to find out whether you get the certificate error too?

Everything is fine. File is 66.4Mb.

**Comment by fenryxo** [comment] 2020-09-06 17:09
Could you post the output of this command?

```
LANG=C flatpak run --command=openssl eu.tiliado.NuvolaAppTidal \
s_client -servername dl.google.com -connect dl.google.com:443 \
-showcerts </dev/null 2>/dev/null
```

**Comment by mirsemen** [comment] 2020-09-07 02:49
> Could you post the output of this command?
> 
> ```
> LANG=C flatpak run --command=openssl eu.tiliado.NuvolaAppTidal \
> s_client -servername dl.google.com -connect dl.google.com:443 \
> -showcerts </dev/null 2>/dev/null
> ```

http://pastebin.calculate-linux.ru/ru/show/144329

**Comment by fenryxo** [comment] 2020-09-09 21:17
Hello @mirsemen. I might be a bug in your distribution. Could you look at flatpak/flatpak#2921 whether it gives you any clues?

**Comment by mirsemen** [comment] 2020-09-10 06:04
> Hello @mirsemen. I might be a bug in your distribution. Could you look at [flatpak/flatpak#2921](https://github.com/flatpak/flatpak/issues/2921) whether it gives you any clues?

Hi! Wow! It helps me a lot! Thanks!

[This](https://github.com/flatpak/flatpak/issues/2921#issuecomment-633745255) was the solution.

**Comment by fenryxo** [comment] 2020-09-10 15:32
Glad to help :-)

**Closed by fenryxo** 2020-09-10 15:32 UTC
Labels: need info, type: bug
